server:
  public:
    address: ":8000"
    cors:
      enabled: true
      allow_origins:
        - "http://localhost:3000"
      allow_credentials: true
  admin:
    address: ":8001"

webauthn:
  relying_party:
    id: "localhost"
    display_name: "Repousse"
    origins:
      - "http://localhost:3000"

database:
  user: postgres
  password: postgres
  host: postgres
  port: "5432"
  database: hanko
  dialect: postgres

secrets:
  keys:
    - "supersecrethankokey32chars123456"

session:
  lifespan: "1h"
  enable_auth_token_header: true
  cookie:
    http_only: false
    same_site: "lax"
    secure: false  # true in production

password:
  enabled: true
  min_length: 8

passcode:
  ttl: 120

email_delivery:
  smtp:
    host: "mailpit"
    port: "1025"
  from_address: noreply@repousse.org
